// Code generated by helmit-generate. DO NOT EDIT.

package v1

import (
	"github.com/wangxn2015/helmit/pkg/kubernetes/resource"
)

type DeploymentsClient interface {
	Deployments() DeploymentsReader
}

func NewDeploymentsClient(resources resource.Client, filter resource.Filter) DeploymentsClient {
	return &deploymentsClient{
		Client: resources,
		filter: filter,
	}
}

type deploymentsClient struct {
	resource.Client
	filter resource.Filter
}

func (c *deploymentsClient) Deployments() DeploymentsReader {
	return NewDeploymentsReader(c.Client, c.filter)
}
