// Code generated by helmit-generate. DO NOT EDIT.

package v1

import (
	"github.com/wangxn2015/helmit/pkg/kubernetes/resource"
)

type Client interface {
	StorageClassesClient
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client:               resources,
		StorageClassesClient: NewStorageClassesClient(resources, filter),
	}
}

type client struct {
	resource.Client
	StorageClassesClient
}
