// Code generated by helmit-generate. DO NOT EDIT.

package v1

import (
	"github.com/wangxn2015/helmit/pkg/kubernetes/resource"
)

type ValidatingWebhookConfigurationsClient interface {
	ValidatingWebhookConfigurations() ValidatingWebhookConfigurationsReader
}

func NewValidatingWebhookConfigurationsClient(resources resource.Client, filter resource.Filter) ValidatingWebhookConfigurationsClient {
	return &validatingWebhookConfigurationsClient{
		Client: resources,
		filter: filter,
	}
}

type validatingWebhookConfigurationsClient struct {
	resource.Client
	filter resource.Filter
}

func (c *validatingWebhookConfigurationsClient) ValidatingWebhookConfigurations() ValidatingWebhookConfigurationsReader {
	return NewValidatingWebhookConfigurationsReader(c.Client, c.filter)
}
